version: "3"
services:
  fuelrod-batch:
    container_name: fuelrod-batch
    image: tsobu/fuelrod-batch:${BATCH_VERSION}
    restart: always
    ports:
      - 9001:9001
    volumes:
      - ${PWD}/log:/log
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - BATCH_CRON=${BATCH_CRON}