server:
  port: 9001

spring:
  application:
    name: fuelrod
  profiles:
    active: dev
  batch:
    job:
      names: "processMessage"
      enabled: true
    initialize-schema: ALWAYS
  main:
    web-application-type: NONE